
import { getLoanIndustry, selectCardNo } from "@/api/loanContract/contract";
export default {
  custombase: [   // 客户基本信息
    { label: "客户号:", type: 'input', disabled: true, keys: "custId" },
    { label: "客户编号:", type: 'input', placeholder: "请输入客户编号", rules: [{ required: true, message: '客户编号不能为空', trigger: 'blur' }], disabled: false, keys: "custno" },
    { label: "客户姓名:", type: 'input', placeholder: "请输入客户姓名", rules: [{ required: true, message: '客户姓名不能为空', trigger: 'blur' }], disabled: true, keys: "custname" },
    { label: "证件类型:", type: 'select', placeholder: "请选择证件类型", rules: [{ required: true, message: '证件类型不能为空', trigger: 'blur' }], disabled: true, keys: "paperkind", keydata: "contract_cert_type" },
    { label: "证件号码:", type: 'input', placeholder: "请输入证件号码", rules: [{ required: true, message: '证件号码不能为空', trigger: 'blur' }], disabled: true, keys: "paperid" },
    { label: "证件有效期:", type: 'daterange', placeholder: "请选择证件有效期", disabled: false, startkey: "certissuedt", endkey: "certexptdt" },
    { label: "出生日期:", type: 'date', placeholder: "请输入出生日期", rules: [{ required: true, message: '出生日期不能为空', trigger: 'blur' }], disabled: false, keys: "birtdate" },
    { label: "性别:", type: 'select', placeholder: "请选择性别", rules: [{ required: true, message: '性别不能为空', trigger: 'blur' }], disabled: true, keys: "sexsign", keydata: "contract_contract_sex" },
    { label: "国籍:", type: 'select', placeholder: "请选择国籍", rules: [{ required: true, message: '国籍不能为空', trigger: 'blur' }], disabled: false, keys: "natisign2", keydata: "contract_natisign2" },
    { label: "民族:", type: 'select', placeholder: "请选择民族", disabled: false, keys: "natisign1", keydata: "contract_natisign1" },
    { label: "婚姻状况:", type: 'select', placeholder: "请选择婚姻状况", rules: [{ required: true, message: '婚姻状况不能为空', trigger: 'blur' }], disabled: true, keys: "marrsign", keydata: "contract_marrsign" },
    { label: "身体状况:", type: 'select', placeholder: "请选择身体状况", disabled: false, keys: "healsign", keydata: "contract_healsign" },
    { label: "移动电话:", type: 'input', placeholder: "请输入移动电话", rules: [{ required: true, message: '移动电话不能为空', trigger: 'blur' }], disabled: true, keys: "mobile" },
    { label: "政治面貌:", type: 'select', placeholder: "请选择政治面貌", rules: [{ required: true, message: '政治面貌不能为空', trigger: 'blur' }], disabled: false, keys: "polihday", keydata: "contract_politicsStatus" },
    { label: "从业状况:", type: 'select', placeholder: "请选择从业状况", disabled: false, keys: "epmstatus", keydata: "contract_workingConditions" },
    { label: "是否企业主:", type: 'select', placeholder: "请选择是否企业主", rules: [{ required: true, message: '是否企业主不能为空', trigger: 'blur' }], disabled: false, keys: "iscorpcharger", keydata: "contract_isEntrepreneur" },
    { label: "最高学历:", type: 'select', placeholder: "请选择最高学历", rules: [{ required: true, message: '最高学历不能为空', trigger: 'blur' }], disabled: false, keys: "educsign", keydata: "contract_highestEducation" },
    { label: "最高学位:", type: 'select', placeholder: "请选择最高学位", rules: [{ required: true, message: '最高学位不能为空', trigger: 'blur' }], disabled: false, keys: "degreesign", keydata: "contract_highestDegree" },
    { label: "借款人性质:", type: 'select', placeholder: "请选择借款人性质", rules: [{ required: true, message: '借款人性质不能为空', trigger: 'blur' }], disabled: true, keys: "customerkind", keydata: "contract_natureOfBorrower" },
    { label: "是否农村住户:", type: 'select', placeholder: "请选择是否农村住户", rules: [{ required: true, message: '是否农村住户不能为空', trigger: 'blur' }], disabled: true, keys: "isagriflag", keydata: "contract_isRuralHouse" },
    { label: "年收入(元):", type: 'input', placeholder: "请输入年收入", rules: [{ required: true, message: '年收入不能为空', trigger: 'blur' }], disabled: false, keys: "moneyPerYear" },
    { label: "是否本行股东:", type: 'select', placeholder: "请选择是否本行股东", rules: [{ required: true, message: '是否本行股东不能为空', trigger: 'blur' }], disabled: false, keys: "stockholderflag", keydata: "contract_isBankShareHolders" },
    { label: "居住状况:", type: 'select', placeholder: "请选择居住状况", rules: [{ required: true, message: '居住状况不能为空', trigger: 'blur' }], disabled: false, keys: "inhabstatsign", keydata: "contract_ResidenceStatus" },
    { label: "行政区划:", type: 'region', placeholder: "请选择行政区划", rules: [{ required: true, message: '行政区划不能为空', trigger: 'blur' }], disabled: false, keys: "areaCodeArray" }
  ],
  mateinfo: [   // 配偶信息
    { label: "客户编号:", type: 'input', rules: [{ required: true, message: '客户编号不能为空', trigger: 'blur' }], disabled: true, keys: "custId" },
    { label: "姓名:", type: 'input', rules: [{ required: true, message: '姓名不能为空', trigger: 'blur' }], placeholder: "请输入姓名", disabled: true, keys: "farmername" },
    { label: "身份证号码:", type: 'input', rules: [{ required: true, message: '身份证号码不能为空', trigger: 'blur' }], placeholder: "请输入身份证号码", disabled: true, keys: "paperid" },
    { label: "性别:", type: 'select', rules: [{ required: true, message: '性别不能为空', trigger: 'blur' }], placeholder: "请选择性别", disabled: true, keys: "sexsign", keydata: "contract_contract_sex" },
    { label: "出生日期:", type: 'date', rules: [{ required: true, message: '出生日期不能为空', trigger: 'blur' }], placeholder: "请输入出生日期", disabled: true, keys: "birtdate" },
    { label: "手机号码:", type: 'input', rules: [{ required: true, message: '手机号码不能为空', trigger: 'blur' }], placeholder: "请输入手机号码", rules: [{ required: true, message: '手机号码不能为空', trigger: 'blur' }], disabled: false, keys: "phone" },
    { label: "健康状况:", type: 'select', rules: [{ required: true, message: '健康状况不能为空', trigger: 'blur' }], placeholder: "请选择健康状况", disabled: false, keys: "healsign", keydata: "contract_healsign" },
    { label: "生活方式:", type: 'select', rules: [{ required: true, message: '生活方式不能为空', trigger: 'blur' }], placeholder: "请选择生活方式", disabled: false, keys: "isbadkind", keydata: "contract_isbadkind" },
    { label: "当前是否欠缴个税:", type: 'select', rules: [{ required: true, message: '是否欠缴个税不能为空', trigger: 'blur' }], placeholder: "请选择当前是否欠缴个税", disabled: false, keys: "isnotaxeflag", keydata: "default_yesorno" },
    { label: "借款历史记录:", type: 'select', rules: [{ required: true, message: '借款历史记录不能为空', trigger: 'blur' }], placeholder: "请选择借款历史记录", disabled: false, keys: "isbankrecordflag", keydata: "contract_yesno" },
    { label: "是否参加医保:", type: 'select', rules: [{ required: true, message: '是否参加医保不能为空', trigger: 'blur' }], placeholder: "请选择是否参加医保", disabled: false, keys: "ishospinsuflag", keydata: "default_yesorno" },
    { label: "社会治安等公共记录:", type: 'select', rules: [{ required: true, message: '社会治安等公共记录不能为空', trigger: 'blur' }], placeholder: "请选择社会治安等公共记录", disabled: false, keys: "socialhonor", keydata: "contract_socialhonor" },
    { label: "有无指定联系人:", type: 'select', rules: [{ required: true, message: '有无指定联系人不能为空', trigger: 'blur' }], placeholder: "请选择有无指定联系人", disabled: false, keys: "iscontactflag", keydata: "contract_iscontactflag" },
    { label: "人寿保险额度:", type: 'input', rules: [{ required: true, message: '人寿保险额度不能为空', trigger: 'blur' }], placeholder: "请输入人寿保险额度", disabled: false, keys: "insurancevalue" },
    { label: "居住地:", type: 'input', rules: [{ required: true, message: '居住地不能为空', trigger: 'blur' }], placeholder: "请输入居住地", disabled: false, keys: "addr" },
    { label: "工作单位:", type: 'select', rules: [{ required: true, message: '工作单位不能为空', trigger: 'blur' }], placeholder: "请选择工作单位", disabled: false, keys: "workcorp", keydata: "contract_workUnit" },
    { label: "职业:", type: 'select', rules: [{ required: true, message: '职业不能为空', trigger: 'blur' }], placeholder: "请选择职业", disabled: false, keys: "vocasign", keydata: "contract_profession" },
    { label: "工作区域:", type: 'select', rules: [{ required: true, message: '工作区域不能为空', trigger: 'blur' }], placeholder: "请选择工作区域", disabled: false, keys: "workaddrflag", keydata: "contract_workingArea" },
    { label: "就业状态:", type: 'select', rules: [{ required: true, message: '就业状态不能为空', trigger: 'blur' }], placeholder: "请选择就业状态", disabled: false, keys: "workstatus", keydata: "contract_employment" },
    { label: "年收入(元):", type: 'input', rules: [{ required: true, message: '年收入不能为空', trigger: 'blur' }], placeholder: "请输入年收入", disabled: false, keys: "yearinco" },
    { label: "文化程度:", type: 'select', rules: [{ required: true, message: '文化程度不能为空', trigger: 'blur' }], placeholder: "请选择文化程度", disabled: false, keys: "educsign", keydata: "contract_culture" },
    { label: "政治面貌:", type: 'select', rules: [{ required: true, message: '政治面貌不能为空', trigger: 'blur' }], placeholder: "请选择政治面貌", disabled: false, keys: "polihday", keydata: "contract_politicsStatus" },
    { label: "是否为户主:", type: 'select', rules: [{ required: true, message: '是否为户主不能为空', trigger: 'blur' }], placeholder: "请选择是否为户主", disabled: true, keys: "isfarmerflag", keydata: "contract_isOwner" }
  ],
  familyinfo: [   // 农户家庭情况
    { label: "档案编号:", type: 'input', placeholder: "请输入档案编号", disabled: false, keys: "farmerid" },
    { label: "邮政编码:", type: 'input', placeholder: "请输入邮政编码", rules: [{ required: true, message: '邮政编码不能为空', trigger: 'blur' }], disabled: false, keys: "post" },
    { label: "当地信用环境:", type: 'select', placeholder: "请选择当地信用环境", rules: [{ required: true, message: '当地信用环境不能为空', trigger: 'blur' }], disabled: false, keys: "locationcredit", keydata: "contract_locationcredit" },
    { label: "详细地址:", type: 'input', placeholder: "请输入详细地址", rules: [{ required: true, message: '详细地址不能为空', trigger: 'blur' }], disabled: false, keys: "farmerdetaaddr" },
    { label: "家庭是否和睦:", type: 'select', placeholder: "请选择家庭是否和睦", rules: [{ required: true, message: '家庭是否和睦不能为空', trigger: 'blur' }], disabled: false, keys: "familyflag", keydata: "default_yesorno" },
    { label: "是否欠缴税费(除个税):", type: 'select', placeholder: "请选择是否欠缴税费(除个税)", rules: [{ required: true, message: '是否欠缴税费不能为空', trigger: 'blur' }], disabled: false, keys: "islacktax", keydata: 'default_yesorno' },
    { label: "主营业务是不是自办实体:", type: 'select', placeholder: "请选择主营业务是不是自办实体", rules: [{ required: true, message: '主营业务是不是自办实体不能为空', trigger: 'blur' }], disabled: false, keys: "isinderstray", keydata: 'default_yesorno' },
    { label: "社会评价(村委会评价):", type: 'select', placeholder: "请选择社会评价(村委会评价)", rules: [{ required: true, message: '社会评价不能为空', trigger: 'blur' }], disabled: false, keys: "socialappraisal", keydata: "contract_socialAppraisal" },
    { label: "生产经营能力:", type: 'select', placeholder: "请选择生产经营能力", rules: [{ required: true, message: '生产经营能力不能为空', trigger: 'blur' }], disabled: false, keys: "treadpower", keydata: "contract_operationCapacity" },
    { label: "生产经营年前景:", type: 'select', placeholder: "请选择生产经营年前景", rules: [{ required: true, message: '生产经营年前景不能为空', trigger: 'blur' }], disabled: false, keys: "treadfuture", keydata: "contract_operationProspect" },
    { label: "家庭人口:", type: 'input', placeholder: "请输入家庭人口", rules: [{ required: true, message: '家庭人口不能为空', trigger: 'blur' }], disabled: false, keys: "farmerfamilysum" },
    {
      label: "参加保险情况:", type: 'checkbox', rules: [{ required: true, message: '参加保险情况不能为空', trigger: 'blur' }], disabled: false, keys: "isinsuranceArray", inline: true, 
      keydata: [
        { label: "医疗保险", id: 1 },
        { label: "财产保险", id: 2 },
        { label: "人寿保险", id: 3 },
        { label: "农业保险", id: 4 },
        { label: "其他", id: 9 }
      ]
    }
  ],
  manageinfo: [   // 经营信息
    { label: "统一社会信用代码:", type: 'input', placeholder: "请输入统一社会信用代码", rules: [{ required: true, message: '统一社会信用代码不能为空', trigger: 'blur' }], disabled: false, keys: "liceid" },
    { label: "经营名称:", type: 'input', placeholder: "请输入经营名称", rules: [{ required: true, message: '经营名称不能为空', trigger: 'blur' }], disabled: false, keys: "dealproj" },
    { label: "类型:", type: 'select', placeholder: "请选择类型", rules: [{ required: true, message: '类型不能为空', trigger: 'blur' }], disabled: false, keys: "licetype", keydata: "contract_licetype" },
    { label: "经营者姓名:", type: 'input', placeholder: "请输入经营者姓名", rules: [{ required: true, message: '经营者姓名不能为空', trigger: 'blur' }], disabled: false, keys: "dealname" },
    { label: "成立日期:", type: 'date', placeholder: "请输入成立日期", rules: [{ required: true, message: '成立日期不能为空', trigger: 'blur' }], disabled: false, keys: "comedate" },
    { label: "注册地址:", type: 'input', placeholder: "请输入注册地址", rules: [{ required: true, message: '注册地址不能为空', trigger: 'blur' }], disabled: false, keys: "liceaddr" }
  ],
  professioninfo: [   // 职业信息
    { label: "职业:", type: 'select', placeholder: "请选择职业", rules: [{ required: true, message: '职业不能为空', trigger: 'blur' }], disabled: false, keys: "vocasign", keydata: "contract_profession" },
    { label: "工作单位:", type: 'input', placeholder: "请输入工作单位", disabled: false, keys: "workcorp" },
    { label: "单位性质:", type: 'select', placeholder: "请选择单位性质", rules: [{ required: true, message: '单位性质不能为空', trigger: 'blur' }], disabled: false, keys: "corpkind", keydata: "contract_unitNature" },
    { label: "行业类别:", type: 'select', placeholder: "请选择行业类别", rules: [{ required: true, message: '行业类别不能为空', trigger: 'blur' }], disabled: false, keys: "waykind", keydata: "contract_industry" }
  ],
  creditrecord: [  // 借款人信贷记录
    { label: "申请业务类型:", type: 'text', keys: "applyBusiType" },
    { label: "产品名称:", type: 'text', keys: "prodname" },
    { label: "产品编号:", type: 'text', keys: "prodid" },
    { label: "调查人:", type: 'text', keys: "nickName" },
    { label: "调查机构:", type: 'text', keys: "deptName" },
    { label: "营销人:", type: 'text', keys: "nickName" },
    { label: "营销机构:", type: 'text', keys: "deptName" },
    { label: "受理人:", type: 'text', keys: "nickName" },
    { label: "受理机构:", type: 'text', keys: "deptName" },
    { label: "调查日期:", type: 'text', keys: "addtime" },
    { label: "业务受理意见:", type: 'text', keys: "busiOpinion" }
  ],
  eloanCard: [     // 合同基本信息
    { label: "合同编号:", type: 'input', placeholder: "请输入合同编号", rules: [{ required: true, message: '合同编号不能为空', trigger: 'blur' }], disabled: true, keys: "contno" },
    { label: "贷款形式:", type: 'select', placeholder: "请选择贷款形式", rules: [{ required: true, message: '贷款形式不能为空', trigger: 'blur' }], disabled: false, keys: "loanform", keydata: "zx2_report_loan_issuance_form" },
    { label: "申请金额(元):", type: 'input', placeholder: "请输入申请金额(元)", rules: [{ required: true, message: '申请金额不能为空', trigger: 'blur' }], disabled: true, keys: "conttotalamt" },
    { label: "申请期限(月):", type: 'input', placeholder: "请输入申请期限(月)", rules: [{ required: true, message: '申请期限不能为空', trigger: 'blur' }], disabled: true, keys: "contterm" },
    { label: "最长用款期限(月):", type: 'input', placeholder: "请输入最长用款期限(月)", rules: [{ required: true, message: '最长用款期限不能为空', trigger: 'blur' }], disabled: true, keys: "advismaxuseterm" },
    { label: "申请日期:", type: 'date', placeholder: "请输入申请日期", rules: [{ required: true, message: '申请日期不能为空', trigger: 'blur' }], disabled: true, keys: "begindate" },
    { label: "到期日期:", type: 'date', placeholder: "请输入到期日期", rules: [{ required: true, message: '到期日期不能为空', trigger: 'blur' }], disabled: true, keys: "enddate" },
    { label: "贷款方式:", type: 'select', placeholder: "请输入贷款方式", rules: [{ required: true, message: '贷款方式不能为空', trigger: 'blur' }], disabled: true, keys: "assukind", keydata: "contract_loan_assukind" },
    { label: "低风险业务类型:", type: 'input', placeholder: "请输入低风险业务类型", disabled: true, keys: "lowRisk" },
    { label: "贷款行业投向:", type: 'cascader', placeholder: "请输入贷款行业投向", rules: [{ required: true, message: '贷款行业投向不能为空', trigger: 'blur' }], disabled: false, keys: "fundputArray", options: getLoanIndustry },
    { label: "贷款质量初分意见:", type: 'select', placeholder: "请输入贷款质量初分意见", rules: [{ required: true, message: '贷款质量初分意见不能为空', trigger: 'blur' }], disabled: false, keys: "riskflag", keydata: "contract_loan_riskflag" },
    { label: "还款方式:", type: 'select', placeholder: "请输入还款方式", rules: [{ required: true, message: '还款方式不能为空', trigger: 'blur' }], disabled: false, keys: "retukind", keydata: "contract_loan_retukind" },
    { label: "资金来源:", type: 'select', placeholder: "请输入资金来源", rules: [{ required: true, message: '资金来源不能为空', trigger: 'blur' }], disabled: false, keys: "funds", keydata: "contract_loan_funds" },
    { label: "贷款用途:", type: 'select', placeholder: "请输入贷款用途", rules: [{ required: true, message: '贷款用途不能为空', trigger: 'blur' }], disabled: false, keys: "loanuse", keydata: "contract_loanuse" },
    { label: "贷款用途说明:", type: 'input', placeholder: "请输入贷款用途说明", disabled: false, keys: "loanusemark" },
    { label: "还款来源说明:", type: 'select', placeholder: "请选择来源说明", disabled: false, keys: "retudesc", keydata: "contract_repaymentExplain" },
    { label: "管户客户经理:", type: 'input', placeholder: "请输入管户客户经理", rules: [{ required: true, message: '管户客户经理不能为空', trigger: 'blur' }], disabled: false, keys: "operid" },
    { label: "管户机构:", type: 'input', placeholder: "请输入管户机构", rules: [{ required: true, message: '管户机构不能为空', trigger: 'blur' }], disabled: false, keys: "bankid" },
    { 
      label: "银行卡卡号:",
      type: 'select',
      $remote: selectCardNo,
      props: { label: 'b151', value: 'b152' },
      remoteKey: "custId",
      placeholder: "请输入银行卡卡号", 
      rules: [{ required: true, message: '银行卡卡号不能为空', trigger: 'blur' }],
      keys: "easyLoanCard"
    }
  ],
  rateInfo: [     // 利率信息
    { label: "利率类型:", type: 'select', placeholder: "请选择利率类型", rules: [{ required: true, message: '利率类型不能为空', trigger: 'blur' }], disabled: false, keys: "intetype", keydata: "contract_rate_intetype" },
    { label: "LPR执行方式:", type: 'input', placeholder: "请输入LPR执行方式", rules: [{ required: true, message: 'LPR执行方式不能为空', trigger: 'blur' }], disabled: false, keys: "lprMode" },
    { label: "利率代码:", type: 'input', placeholder: "请输入利率代码", rules: [{ required: true, message: '利率代码不能为空', trigger: 'blur' }], disabled: true, keys: "ratenote" },
    { label: "基准利率(%):", type: 'input', placeholder: "请输入基准利率(%)", rules: [{ required: true, message: '基准利率不能为空', trigger: 'blur' }], disabled: true, keys: "basicinterate" },
    { label: "贷款利率:", type: 'input', placeholder: "请输入贷款利率", rules: [{ required: true, message: '贷款利率不能为空', trigger: 'blur' }], disabled: true, keys: "loanrate" },
    { label: "利率调整方式:", type: 'select', placeholder: "请输入利率调整方式", rules: [{ required: true, message: '利率调整方式不能为空', trigger: 'blur' }], disabled: true, keys: "inteadjukind", keydata: "contract_loan_inteadjukind" },
    { label: "逾期利率浮动比:", type: 'input', placeholder: "请输入逾期利率浮动比", rules: [{ required: true, message: '逾期利率浮动比不能为空', trigger: 'blur' }], disabled: true, keys: "floatfinerate" },
    { label: "逾期利率(%):", type: 'input', placeholder: "请输入逾期利率(%)", rules: [{ required: true, message: '逾期利率不能为空', trigger: 'blur' }], disabled: true, keys: "finerate" }
  ],
  guaranteeinfo: [  // 担保信息
    { label: "担保合同编号:", type: 'input', placeholder: "请输入担保合同编号", rules: [{ required: true, message: '担保合同编号不能为空', trigger: 'blur' }], disabled: true, keys: "assucontno" },
    { label: "担保合同类型:", type: 'select', placeholder: "请选择担保合同类型", rules: [{ required: true, message: '担保合同类型不能为空', trigger: 'blur' }], keys: "assuconttype", keydata: "contract_assuconttype" },
    { label: "担保方式:", type: 'text', rules: [{ required: true, message: '担保方式不能为空', trigger: 'blur' }], keys: "assutype", keydata: "contract_contassutype" },
    { label: "保证人姓名:", type: 'text', rules: [{ required: true, message: '保证人姓名不能为空', trigger: 'blur' }], keys: "assucustname" },
    { label: "保证人身份证号:", type: 'text', rules: [{ required: true, message: '保证人身份证号不能为空', trigger: 'blur' }], keys: "assucustidCard" },
    { label: "保证担保类型:", type: 'text', rules: [{ required: true, message: '保证担保类型不能为空', trigger: 'blur' }], keys: "guaranteetype", keydata: "contract_ensutype" },
    { label: "担保币种:", type: 'input', placeholder: "请输入担保币种", rules: [{ required: true, message: '担保币种不能为空', trigger: 'blur' }], keys: "assusign" },
    { label: "已提供担保额:", type: 'input', placeholder: "请输入已提供担保额", rules: [{ required: true, message: '已提供担保额不能为空', trigger: 'blur' }], keys: "assuuseamt" },
    { label: "担保金额(元):", type: 'input', placeholder: "请输入担保金额", rules: [{ required: true, message: '担保金额不能为空', trigger: 'blur' }], keys: "assuamt" },
    { label: "需要说明的情况:", type: 'textarea', placeholder: "请输入其他需要说明的情况", rules: [{ required: true, message: '需要说明的情况不能为空', trigger: 'blur' }], keys: "othremark", inline: true }
  ],
  mortgageinfo: [  // 押品信息
    { label: "押品编号:", type: 'text', rules: [{ required: true, message: '押品编号不能为空', trigger: 'blur' }], placeholder: "请输入押品编号", keys: "assuid" },
    { label: "押品名称:", type: 'input', rules: [{ required: true, message: '押品名称不能为空', trigger: 'blur' }], disabled: true, placeholder: "请输入押品名称", keys: "assuname" },
    { label: "担保方式:", type: 'select', rules: [{ required: true, message: '担保方式不能为空', trigger: 'blur' }], placeholder: "请选择担保方式", disabled: true, keys: "assutype", keydata: "contract_contassutype" },
    { label: "担保金额:", type: 'text', rules: [{ required: true, message: '担保金额不能为空', trigger: 'blur' }], placeholder: "请输入担保金额", keys: "assuamt" },
    { label: "押品类别编号:", type: 'input', rules: [{ required: true, message: '押品类别编号不能为空', trigger: 'blur' }], disabled: true, placeholder: "请输入押品类别编号", keys: "impakind" },
    { label: "权利完整性:", type: 'select', rules: [{ required: true, message: '权利完整性不能为空', trigger: 'blur' }], placeholder: "请选择权利完整性", keys: "rightscardcomplete", keydata: "rightscardcomplete" },
    { label: "权利证书类型:", type: 'select', rules: [{ required: true, message: '权利证书类型不能为空', trigger: 'blur' }], placeholder: "请选择权利证书类型", keys: "impacertkind", keydata: "impacertkind" },
    { label: "权利证书号码:", type: 'input', rules: [{ required: true, message: '权利证书号码不能为空', trigger: 'blur' }], placeholder: "请输入权利证书号码", keys: "impacertno" },
    { label: "取得途径:", type: 'select', rules: [{ required: true, message: '取得途径不能为空', trigger: 'blur' }], placeholder: "请选择取得途径", keys: "impagainkind", keydata: "impagainkind" },
    { label: "担保权设定生效方式:", type: 'select', rules: [{ required: true, message: '担保权设定生效方式不能为空', trigger: 'blur' }], placeholder: "请选择担保权设定生效方式", keys: "assueffkind", keydata: "assueffkind" },
    { label: "币种:", type: 'input', rules: [{ required: true, message: '币种不能为空', trigger: 'blur' }], placeholder: "请输入币种", keys: "originsign" },
    { label: "原值:", type: 'input', placeholder: "请输入原值", keys: "originvalue" },
    { label: "评估类型:", type: 'select', rules: [{ required: true, message: '评估类型不能为空', trigger: 'blur' }], placeholder: "请选择评估类型", keys: "evaltype", keydata: "evaltype" },
    { label: "评估方法:", type: 'select', placeholder: "请选择评估方法", keys: "evalmethod", keydata: "evalmethod" },
    { label: "评估日期:", type: 'date', rules: [{ required: true, message: '评估日期不能为空', trigger: 'blur' }], placeholder: "请选择评估日期", keys: "evaldate" },
    { label: "评估币种:", type: 'input', rules: [{ required: true, message: '评估币种不能为空', trigger: 'blur' }], placeholder: "请输入评估币种", keys: "evalsign" },
    { label: "评估金额:", type: 'input', rules: [{ required: true, message: '评估金额不能为空', trigger: 'blur' }], placeholder: "请输入评估金额", keys: "evalvalue" },
    { label: "押品价值确定方式:", type: 'select', placeholder: "请选择押品价值确定方式", keys: "estimkind", keydata: "estimkind" },
    { label: "确认日期:", type: 'date', placeholder: "请选择确认日期", keys: "estimdate" },
    { label: "确认金额:", type: 'input', rules: [{ required: true, message: '确认金额不能为空', trigger: 'blur' }], placeholder: "请输入确认金额", keys: "estimvalue" },
    { label: "本次设定权利金额:", type: 'input', rules: [{ required: true, message: '本次设定权利金额不能为空', trigger: 'blur' }], placeholder: "请输入本次设定权利金额", keys: "rightamountset" },
    { label: "受偿顺序:", type: 'select', placeholder: "请选择受偿顺序", keys: "liqorder", keydata: "liqorder" },
    { label: "受偿人名称:", type: 'input', placeholder: "请输入受偿人名称", keys: "liqpsnname" }
  ],
  houseinfo: [    // 房产信息
    { label: "押品编号:", type: 'text', placeholder: "请输入押品编号", rules: [{ required: true, message: '押品编号不能为空', trigger: 'blur' }], keys: "assuid" },
    { label: "所处位置:", type: 'region', placeholder: "请输入所处位置", rules: [{ required: true, message: '所处位置不能为空', trigger: 'blur' }], keys: "loacatIdArray", labelkey: "location" },
    { label: "坐落位置详细说明:", type: 'input', placeholder: "请输入坐落位置详细说明", rules: [{ required: true, message: '坐落位置详细说明不能为空', trigger: 'blur' }], keys: "detailedaddr" },
    { label: "小区:", type: 'input', placeholder: "请输入小区", rules: [{ required: true, message: '小区不能为空', trigger: 'blur' }], keys: "neighborhood" },
    { label: "管理状态:", type: 'select', placeholder: "请选择管理状态", rules: [{ required: true, message: '管理状态不能为空', trigger: 'blur' }], keys: "managestate", keydata: 'contract_managestate' },
    { label: "房号:", type: 'input', placeholder: "请输入房号", rules: [{ required: true, message: '房号不能为空', trigger: 'blur' }], keys: "roomnumber" },
    { label: "楼层总层数:", type: 'input', placeholder: "请输入楼层总层数", rules: [{ required: true, message: '楼层总层数不能为空', trigger: 'blur' }], keys: "totalfloor" },
    { label: "建筑面积:", type: 'input', placeholder: "请输入建筑面积", rules: [{ required: true, message: '建筑面积不能为空', trigger: 'blur' }], keys: "housearea" },
    { label: "维护状况:", type: 'select', placeholder: "请选择维护状况", rules: [{ required: true, message: '维护状况不能为空', trigger: 'blur' }], keys: "maintenancecond", keydata: 'contract_maintenancecond' },
    { label: "户型:", type: 'select', placeholder: "请选择户型", rules: [{ required: true, message: '户型不能为空', trigger: 'blur' }], keys: "sized", keydata: 'contract_sized' },
    { label: "有无私家车库:", type: 'select', placeholder: "请选择有无私家车库", rules: [{ required: true, message: '有无私家车库不能为空', trigger: 'blur' }], keys: "havegarage", keydata: "contract_havenull" },
    { label: "有无土地使用权证:", type: 'select', placeholder: "请选择有无土地使用权证", rules: [{ required: true, message: '有无土地使用权证不能为空', trigger: 'blur' }], keys: "havelandcard", keydata: "contract_havenull" },
    { label: "土地使用权类型:", type: 'select', placeholder: "请选择土地使用权类型", rules: [{ required: true, message: '土地使用权类型不能为空', trigger: 'blur' }], keys: "landtype", keydata: "contract_landtype"},
    { label: "土地使用权证书号:", type: 'input', placeholder: "请输入土地使用权证书号", keys: "landcardno", link: { key: "havelandcard", value: 0 } },
    { label: "土地使用权期限:", type: 'daterange', placeholder: "请选择土地使用权期限", startkey: "landstartdate", endkey: "landenddate", link: { key: "havelandcard", value: 0 } },
    { label: "购买时间:", type: 'date', placeholder: "请选择购买时间", rules: [{ required: true, message: '购买时间不能为空', trigger: 'blur' }], keys: "buytime" },
    { label: "购置价格（元）:", type: 'input', placeholder: "请输入购置价格（元）", rules: [{ required: true, message: '购置价格不能为空', trigger: 'blur' }], keys: "purchaseprice" },
    { label: "购置种类:", type: 'select', placeholder: "请选择购置种类", keys: "buykind", keydata: "contract_buykind" },
    { label: "资产状态:", type: 'select', placeholder: "请选择资产状态", keys: "assetstate", keydata: "contract_assetstate" },
    { label: "房屋性质:", type: 'select', placeholder: "请选择房屋性质", rules: [{ required: true, message: '房屋性质不能为空', trigger: 'blur' }], keys: "houseproperty", keydata: "contract_houseproperty" },
    { label: "是否出租:", type: 'select', placeholder: "请选择是否出租", keys: "leaseflag", keydata: "contract_yesno" },
    { label: "是否处于预告登记阶段:", type: 'select', placeholder: "请选择是否处于预告登记阶段", keys: "regstage", keydata: "contract_yesno" },
    { label: "预告登记权利号:", type: 'input', placeholder: "请输入预告登记权利号", keys: "regrightsno", link: { key: "regstage", value: 0 } },
    { label: "预告登记日期:", type: 'date', placeholder: "请选择预告登记日期", keys: "regdate", link: { key: "regstage", value: 0 } },
    { label: "可办理所有权登记起始日期:", type: 'date', placeholder: "请选择可办理所有权登记起始日期", keys: "ownershipdate" }
  ],
  personalLoaninfo: [   // 个贷合同基本信息
    { label: "客户编号:", type: 'text', keys: "custno" },
    { label: "客户名称:", type: 'text', keys: "custname" },
    { label: "产品编号:", type: 'text', keys: "prodid" },
    { label: "产品名称:", type: 'text', keys: "prodname" },
    { label: "卡号:", type: 'text', keys: "easyLoanCard" },
    { label: "币种:", type: 'text', keys: "currsign" },
    { label: "批准金额(元):", type: 'text', keys: "apprtotalamt" },
    { label: "合同金额(元):", type: 'text', keys: "conttotalamt" },
    { label: "批准期限(月):", type: 'text', keys: "apptterm" },
    { label: "合同期限(月):", type: 'text', keys: "contterm" },
    { label: "最长用款期限(月):", type: 'text', keys: "advismaxuseterm" },
    { label: "合同起始日期:", type: 'text', keys: "begindate" },
    { label: "合同到期日期:", type: 'text', keys: "enddate" },
    { label: "贷款方式:", type: 'text', keys: "assukind", keydata: "contract_loan_assukind" },
    { label: "贷款质量:", type: 'text', keys: "riskflag", keydata: "contract_loan_assukind", keydata: "contract_loan_riskflag" },
    { label: "贷款用途:", type: 'text', keys: "loanuse", keydata: "contract_loanuse" },
    { label: "放款渠道:", type: 'text', keys: "relechannel", keydata: "contract_relechannel" },
    { label: "贷款用途说明:", type: 'text', keys: "loanusemark", inline: true },
    { label: "还款来源说明:", type: 'text', keys: "retudesc", inline: true },
    { label: "贷款投向行业:", type: 'text', keys: "fundputName" },
    { label: "贷款形式:", type: 'text', keys: "loanform", keydata: "zx2_report_loan_issuance_form" },
    { label: "资金来源:", type: 'text', keys: "funds", keydata: "contract_loan_funds" },
    { label: "是否指定费率信息:", type: 'text', keys: "issetcostrate", keydata: 'contract_yesno' },
    { label: "是否涉农贷款:", type: 'select', placeholder: "请选择是否涉农贷款", rules: [{ required: true, message: '是否涉农贷款不能为空', trigger: 'blur' }], keys: "isagriflag", keydata: 'contract_yesno', inline: true },
    { 
      label: "涉农贷款用途:", 
      type: 'select', 
      placeholder: "请选择涉农贷款用途", 
      rules: [{ required: true, message: '涉农贷款用途不能为空', trigger: 'blur' }], 
      keys: "isagridesc", 
      link: { key: "isagriflag", value: 0 },
      keydata: 'contract_isagridesc', 
      inline: true 
    }
    // { label: "精准扶贫标识:", type: 'text', keys: "povertyRelief" },
    // { label: "劝耕贷:", type: 'text', keys: "AdvisePlow" }
  ],
  payinfo: [    // 支付信息
    { label: "用款方式:", type: 'text', keys: "useamtkind", keydata: "contract_useamtkind" },
    { label: "支付方式:", type: 'text', keys: "paymode", keydata: "contract_paymode" },
    { label: "借款人账号:", type: 'text', keys: "indesubsacno" },
    { label: "借款人户名:", type: 'text', keys: "indesubsac" }
  ],
  repaymentinfo: [    // 还款信息
    // { label: "是否贴息:", type: 'text', keys: "isSoft" },
    { label: "还款方式:", type: 'text', keys: "retukind", keydata: "contract_loan_retukind" },
    { label: "扣款方式:", type: 'text', keys: "subsflag", keydata: "contract_subsflag" },
    { label: "结息方式:", type: 'text', keys: "intebalkind", keydata: "contract-intebalkind" },
    // { label: "转逾期宽限天数:", type: 'text', keys: "graceDays" },
    { label: "委托扣款账号:", type: 'text', keys: "depesubsacno" },
    { label: "委托扣款户名:", type: 'text', keys: "depesubsac" },
    { label: "是否计算复利:", type: 'text', keys: "sbfineflag", keydata: 'contract_yesno' },
    { label: "执行利率(年):", type: 'text', keys: "loanrate" }
  ],
  otherinfo: [    // 其他信息
    { label: "争议解决方式:", type: 'text', keys: "dispresokind", keydata: "contract_dispresokind" },
    { label: "主责任人:", type: 'text', keys: "liableperson" },
    { label: "放款前提条件:", type: 'input', placeholder: "请输入放款前提条件", disabled: false, keys: "loanConditions", inline: true }
  ],
  guarantycontractinfo: [   // 担保合同信息
    { label: "担保方式:", type: 'text', keys: "assutype", keydata: "contract_contassutype" },
    { label: "保证人姓名:", type: 'text', keys: "assucustname" },
    { label: "保证人身份证号:", type: 'text', keys: "assucustidCard" },
    { label: "保证担保类型:", type: 'text', keys: "guaranteetype", keydata: "contract_ensutype" },
    { label: "担保币种:", type: 'text', keys: "assusign" },
    { label: "已提供担保金额(元):", type: 'text', keys: "assuuseamt" },
    { label: "担保金额(元):", type: 'text', keys: "assuamt" }
  ]
}